import swaggerJSDoc from "swagger-jsdoc";
import swaggerUi from "swagger-ui-express";
import { Express } from "express";
import path from "path";
// import { fileURLToPath } from "url";

// const __filename = fileURLToPath(import.meta.url);
// const __dirname = path.dirname(__filename);

export function setupSwagger(app: Express, serviceName: string) {
  const root = process.cwd();
  const options = {
    definition: {
      openapi: "3.0.0",
      info: {
        title: `${serviceName} API`,
        version: "1.0.0",
        description: `Autogenerated API docs for ${serviceName}`,
      },
    },
    // apis: ["./**/*.js", "./src/routes/**/*.ts"],
    apis: [
      path.join(root, `apps/${serviceName.toLowerCase()}/src/routes/**/*.ts`),
    ],
  };

  const swaggerSpec = swaggerJSDoc(options);

  // Serve UI and JSON
  app.use("/docs", swaggerUi.serve, swaggerUi.setup(swaggerSpec));
  app.get("/docs-json", (req, res) => res.json(swaggerSpec));
}
